import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

export type ExportFormat = "pdf" | "docx";
export type ExportDocumentType = "cv" | "cover";

type ExportInput = {
  content: string;
  documentType: ExportDocumentType;
  jobTitle?: string;
  company?: string;
  applicantName?: string;
  accentColor?: string;
};

export function buildExportFilename(input: ExportInput, format: ExportFormat) {
  const applicant = slugify(input.applicantName || inferApplicantName(input.content) || "applicant");
  const documentType = input.documentType === "cv" ? "cv" : "coverletter";
  const company = slugify(input.company || "company");
  return `${applicant}-${documentType}-${company}.${format}`;
}

export async function buildDocx(input: ExportInput) {
  const title =
    input.documentType === "cv"
      ? input.applicantName?.trim() || inferApplicantName(input.content) || "Curriculum Vitae"
      : "Cover Letter";
  const subtitle = [input.jobTitle, input.company].filter(Boolean).join(" at ");
  const accent = normalizeHex(input.accentColor);
  const paragraphs = normalizeLines(input.content).map((line) => {
    const style = getLineStyle(line);
    const text = style.kind === "bullet" ? line.replace(/^[-•]\s+/, "") : line;

    return new Paragraph({
      spacing: { after: line ? (style.kind === "heading" ? 180 : 120) : 80 },
      bullet: style.kind === "bullet" ? { level: 0 } : undefined,
      children: [
        new TextRun({
          text: text || " ",
          bold: style.kind === "heading",
          color: style.kind === "heading" ? accent.replace("#", "") : "151816",
          size: style.kind === "heading" ? 21 : 22,
          font: "Aptos",
          allCaps: style.kind === "heading",
        }),
      ],
    });
  });

  const document = new Document({
    creator: "Boltiply",
    description: "Generated by Boltiply",
    title,
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 720,
              right: 720,
              bottom: 720,
              left: 720,
            },
          },
        },
        children: [
          new Paragraph({
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { after: 120 },
            children: [
              new TextRun({
                text: title,
                bold: true,
                size: 34,
                font: "Aptos Display",
                color: input.documentType === "cv" ? accent.replace("#", "") : "151816",
              }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { after: 360 },
            children: [
              new TextRun({
                text: subtitle || "Generated application document",
                color: "5F6F66",
                size: 20,
                font: "Aptos",
              }),
            ],
          }),
          ...paragraphs,
        ],
      },
    ],
  });

  return Packer.toBuffer(document);
}

export async function buildPdf(input: ExportInput) {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const title =
    input.documentType === "cv"
      ? input.applicantName?.trim() || inferApplicantName(input.content) || "Curriculum Vitae"
      : "Cover Letter";
  const subtitle = [input.jobTitle, input.company].filter(Boolean).join(" at ");
  const accent = hexToRgb(normalizeHex(input.accentColor));
  const pageSize: [number, number] = [595.28, 841.89];
  const margin = 54;
  const width = pageSize[0] - margin * 2;
  let page = pdf.addPage(pageSize);
  let y = pageSize[1] - margin;

  page.drawText(title, {
    x: margin,
    y,
    size: 20,
    font: bold,
    color: input.documentType === "cv" ? accent : rgb(0.05, 0.09, 0.07),
  });
  y -= 22;

  page.drawText(subtitle || "Generated application document", {
    x: margin,
    y,
    size: 10,
    font: regular,
    color: rgb(0.36, 0.43, 0.39),
  });
  y -= 28;

  for (const line of normalizeLines(input.content)) {
    const style = getLineStyle(line);
    const text = style.kind === "bullet" ? `• ${line.replace(/^[-•]\s+/, "")}` : line;
    const font = style.kind === "heading" ? bold : regular;
    const size = style.kind === "heading" ? 10 : 10.5;
    const wrapped = wrapLine(text, font, size, width);
    const outputLines = wrapped.length ? wrapped : [""];

    for (const outputLine of outputLines) {
      if (y < margin) {
        page = pdf.addPage(pageSize);
        y = pageSize[1] - margin;
      }

      page.drawText(outputLine, {
        x: margin,
        y,
        size,
        font,
        color: style.kind === "heading" ? accent : rgb(0.08, 0.09, 0.08),
      });
      y -= outputLine ? (style.kind === "heading" ? 17 : 15) : 9;
    }
  }

  return pdf.save();
}

function normalizeLines(content: string) {
  return content
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) =>
      line
        .replace(/\*\*(.*?)\*\*/g, "$1")
        .replace(/__(.*?)__/g, "$1")
        .replace(/\*(.*?)\*/g, "$1")
        .replace(/^#{1,6}\s+/, "")
        .replace(/^\s*[*]\s+/, "- ")
        .replace(/\*+/g, "")
        .trimEnd(),
    );
}

function wrapLine(line: string, font: Awaited<ReturnType<PDFDocument["embedFont"]>>, size: number, maxWidth: number) {
  const words = line.split(/\s+/);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
      current = candidate;
    } else {
      if (current) lines.push(current);
      current = word;
    }
  }

  if (current) lines.push(current);
  return lines;
}

function slugify(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 40);
}

function inferApplicantName(content: string) {
  return normalizeLines(content).find((line) => {
    const trimmed = line.trim();
    return trimmed && trimmed.length <= 48 && !/^[-•]\s+/.test(trimmed);
  });
}

function normalizeHex(value = "#05775B") {
  return /^#[0-9A-Fa-f]{6}$/.test(value) ? value.toUpperCase() : "#05775B";
}

function hexToRgb(hex: string) {
  const red = Number.parseInt(hex.slice(1, 3), 16) / 255;
  const green = Number.parseInt(hex.slice(3, 5), 16) / 255;
  const blue = Number.parseInt(hex.slice(5, 7), 16) / 255;
  return rgb(red, green, blue);
}

function getLineStyle(line: string) {
  const trimmed = line.trim();
  const isBullet = /^[-•]\s+/.test(trimmed);
  const isHeading =
    !isBullet &&
    trimmed.length <= 48 &&
    Boolean(trimmed) &&
    (trimmed === trimmed.toUpperCase() || /^[A-Z][A-Za-z\s/&]+:$/.test(trimmed));

  return {
    kind: isHeading ? "heading" : isBullet ? "bullet" : "body",
  } as const;
}
